services:
  - type: web
    env: node
    name: mks-backend-challenge
    repo: https://github.com/vitorhvieira/mks-backend-challenge
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nestjs-postgres
          property: connectionString
      - key: REDIS_URL
        value: redis://red-cphn09ol6cac73a4ak90:6379
      - key: SECRET_KEY
        value: '123UmaSenhaSeguraQualquer'
    regions:
      - oregon
    autoDeploy: true

databases:
  - type: postgres
    name: nestjs-postgres
    plan: free
    region: oregon

  - type: redis
    name: nestjs-redis
    plan: free
    region: oregon
