services:
  - type: web
    env: node
    name: mks-backend-challenge
    repo: https://github.com/vitorhvieira/mks-backend-challenge
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        value: ${DATAVASE_URL}
      - key: REDIS_URL
        value: ${REDIS_URL}
      - key: SECRET_KEY
        value: ${SECRET_KEY}
    autoDeploy: true
